### ISSUE TITLE
Video settings mostly invisible

### ISSUE THREAD

**Issue by loopeniledam** [FlashyReese/reeses-sodium-options#30]
Hi, I've installed FO in MultiMC but had to disable your mod because the video settings screen was mostly invisible. 

Log from MultiMC is here: https://paste.ee/p/h0SGL

Screenshot of problem:
![Screenshot 2022-03-03 at 15 30 17](https://user-images.githubusercontent.com/100861413/156603269-19b13c41-37d0-4144-9e18-338529afdb36.png)

Let me know if you want more info.
Madeline

**Comment by FlashyReese** [comment]
Update to `1.4.1`, let me know if it solves your issue.

**Comment by FlashyReese** [comment]
Sorry, I just realize that I had placed a Minecraft version lock, this issue should be solved in the 1.18.2 release. Meanwhile don't disable `Reduce Resolution on macOS` with Sodium Extra or you can use [this nightly build](https://github.com/FlashyReese/reeses-sodium-options/suites/5365705356/artifacts/168234472).

**Comment by Madis0** [comment]
> Update to `1.4.1`, let me know if it solves your issue.

They said it does indeed solve this issue.

**Comment by loopeniledam** [comment]
"reduce_resolution_on_mac": true was already set and so that didn't solve the issue.

As Madis wrote, FO version 3.3.0-alpha.2 fixes the issue.

Thanks!

**Comment by FlashyReese** [comment]
Interesting, I'm closing this since issue #4 has already been resolved. Oddly enough your entire user interface was invisible.
